project:
  type: website

website:
  title: "Denver Crime Analysis: 2010-2021"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

