---
title: "Home"
code-tools: false
---

## Overview
This analysis looks at crime data for Denver, Colorado from 2010 to 2021. A number of analyses will be done, each focusing on a different type of crime in a particular time and part of the city. In each analysis observations of crime patterns will be reported and recommendations, if relevant, will be made in the conclusions section. In an effort to create reproducible research, each page is a self contained analysis and the R code is available embedded in each page for quick reference but also available on Github.

:::{.callout-note}
## Viewing the code
To view the code used in this analysis, click the `> Code` accordions to expand the code blocks. The `</>Code` dropdowns at the top of every page will let you view the entire quarto markdown file used to create the page. All data and code is available for viewing and download on [Github](https://github.com/TrippBishopStats/Denver-Crime-Analysis).
:::

## Analyses

- [Robbery hot spots in east Denver, 2021](robbery-hotspots.html)

## Data sources

The data for this project came from these sources:

- <a href="https://data.colorado.gov/Municipal/Denver-Statistical-Neighborhoods/6g4b-w8bd" target="_blank">Denver Statistical Neighborhoods<a>
- <a href="https://www.denvergov.org/opendata/dataset/city-and-county-of-denver-crime" target="_blank">Open Data Catalog<a>
- <a href="https://www.denvergov.org/media/gis/DataCatalog/crime/pdf/NIBRS_Crime_Types.pdf" target="_blank">NIBRS Crime Type Definitions<a>
- <a href="https://data.colorado.gov/Demographics/Census-Tracts-in-Colorado-2020/7t53-5gfx/about_data" target="_blank">Census Tracts in Colorado 2020<a>
- <a href="https://wiki.openstreetmap.org/wiki/Key:highway" target="_blank">OpenStreetMap<a>

## References

The following resources were used for background information and context in spatial data analysis and crime mapping.

- <a href="https://r-spatial.org/book/" target="_blank">Spatial Data Science<a>
- <a href="http://books.lesscrime.info/learncrimemapping/" target="_blank">Learn Crime Mapping<a>
